services:
  app:
    image: localhost/goldfish:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis
  redis:
    image: valkey/valkey:8
    ports:
      - "127.0.0.1:6379:6379"
  caddy:
    image: caddy:2
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
      - redis
